plugins {
    id 'java'
    id 'eclipse'
    id 'application'
    id 'maven-publish'
    id 'com.jfrog.artifactory' version '5.2.5'
}

application {
    mainClass = 'hello.HelloWorld'
}

repositories { 
    maven {
        url 'https://trial7bi9lt.jfrog.io/artifactory/default-gradle-dev'
    }
    mavenCentral()
    google()
}

jar {
    archiveBaseName = 'gs-gradle'
    archiveVersion = '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation "joda-time:joda-time:2.2"
    testImplementation "junit:junit:4.12"
}

publishing {
    publications {
        jar(MavenPublication) {
            groupId 'cursojenkinsmac'
            artifactId 'gs-gradle'
            version '1.0'
            from components.java
        }
    }
}

// Configuración de Artifactory
artifactory {
    contextUrl = 'https://trial7bi9lt.jfrog.io/artifactory'

    clientConfig.resolver.repoKey = 'default-gradle-dev'

    publish {
        repository {
            repoKey = 'default-gradle-dev-local'
            // username = "${artifactory_user}"
            // password = "${artifactory_password}"
        }
        defaults {
            publications('jar')
            publishArtifacts = true
            publishPom = true
        }
    }
}
