buildscript {
    repositories {
        mavenCentral()

    }
    dependencies {
        //Check for the latest version here: http://plugins.gradle.org/plugin/com.jfrog.artifactory
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4+"
    }
}

plugins {
    id 'java'
    id 'eclipse'
    id 'application'
    id 'maven-publish'
    id 'com.jfrog.artifactory' version '5.2.5'
}

application {
    mainClass = 'hello.HelloWorld'
}

// tag::repositories[]
repositories { 
    mavenCentral()
    google()
}
// end::repositories[]

// tag::jar[]
jar {
    archiveBaseName = 'gs-gradle'
    archiveVersion =  '0.1.0'
}
// end::jar[]

// tag::dependencies[]
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
implementation "joda-time:joda-time:2.2"
    testImplementation "junit:junit:4.12"
}
// end::dependencies[]

// tag::wrapper[]
// end::wrapper[]

// publication
publishing {
    publications {
        jar(MavenPublication) {
            groupId 'cursojenkinsmac'
            artifactId 'gs-gradle'
            version '1.0'
            from components.java
        }
    }
}

// artifactory configuration


allprojects {
    apply plugin: "com.jfrog.artifactory"
}

artifactory {
    publish {
        repository {
            repoKey = 'default-gradle-dev-local'
            maven = true
        }
        defaults {
            publications('jar')
            publishArtifacts = true
            publishPom = true
        }
    }
    resolve {
        repository {
            repoKey = 'default-gradle-dev'
            maven = true

        }
    }
}
